#!/bin/env python3

# defining some global varible (to replace with configuration)

# account names
account_fee = "Expenses:Taxes:Kraken"
account = "Assets:Kraken"

# filename for the timestamp
filename_timestamp = "data/timestamp"

# ledger filename
filename_ledger = "data/ledger_kraken.log"

# filename keys
filename_keys = "keys/albus-test.key"

# timeout
timeout = 5


import krakenex

from functions import sync

    
    
if __name__ == '__main__':
    """
    Describe what it does 
    """
    # init krakenex API
    kraken = krakenex.API()
    kraken.load_key(filename_keys)
    
    # connection handler. \todo set timeout variable properly (depending on tier)
    #conn = kraken.Connection("api.kraken.com",timeout=timeout)
    
    sync(kraken, filename_timestamp, filename_ledger, timeout)
