#!/bin/env python3

# defining some global varible (to replace with configuration)

# account names
account_fee = "Expenses:Taxes:Kraken"
account = "Assets:Kraken"

# filename for the timestamp
filename_timestamp = "data/timestamp"

# ledger filename
filename_ledger = "data/ledger_kraken.log"

# filename keys
filename_keys = "keys/albus-test.key"

# timeout
timeout = 5


from kraken import Kraken

from functions import sync

    
    
if __name__ == '__main__':
    """
    Describe what it does 
    """
    # init krakenex API
    kraken = Kraken()
    kraken.load_key(filename_keys)
        
    sync(kraken, filename_timestamp, filename_ledger, timeout,
         account_fee = account_fee, account = account)
